version: '3.7'

services:

  arc-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/arc-frontend'
      - '/arc-frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
