version: '3.7'

services:

  sample:
    container_name: arc-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/arc-frontend'
      - '/arc-frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
