version: '3.7'

services:

  arc-frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - '../:/arc-frontend'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
